model:
  path: "/home/kopal/language-neuron-detection/data/7_finetuning/whole_model_small_lr/checkpoint-30000"
  tokenizer_path: "/home/kopal/language-neuron-detection/data/7_finetuning/whole_model_small_lr/checkpoint-30000"

evaluation:
  dataset_hf_path: "google/wiki40b"
  max_length: 512
  stride: 256
  save_path: "results-wiki-5k"
  streaming: true

use_fix_serialized_bytes: true
max_samples: 5000 # 1000 # null for full dataset

datasets:
  eng_Latn:
    path: ${evaluation.dataset_hf_path}
    subset_name: "en" # "" for datasets without subsets
    split: "validation"
    text_field: "text"
    max_samples: ${max_samples} 
    
  cze_Latn:
    path: ${evaluation.dataset_hf_path}
    subset_name: "cs" # "" for datasets without subsets
    split: "validation"
    text_field: "text"
    max_samples: ${max_samples} 
  
  deu_Latn:
    path: ${evaluation.dataset_hf_path}
    subset_name: "de" # "" for datasets without subsets
    split: "validation"
    text_field: "text"
    max_samples: ${max_samples} 
  
  spa_Latn:
    path: ${evaluation.dataset_hf_path}
    subset_name: "es" # "" for datasets without subsets
    split: "validation"
    text_field: "text"
    max_samples: ${max_samples} 
  
  fra_Latn:
    path: ${evaluation.dataset_hf_path}
    subset_name: "fr" # "" for datasets without subsets
    split: "validation"
    text_field: "text"
    max_samples: ${max_samples} 
