build_order:
  - run_args
  - args
  - callbacks
  - dataset
  - dataset_train
  - dataset_valid
  - tokenizer
  - model
  - trainer

run_args:
  project_name: language_neuron_detection
  experiment_class: ${method:finetuning_impl.7_finetuning.Experiment}
  experiment_name: czech-finetuing-20-latn-large-lr
  description: Czech FineWeb next-token training with non-English language-neuron updates only
  tracker:
    _target_: runexp.MLFlowTracker
    project_name: ${run_args.project_name}
    experiment_name: ${run_args.experiment_name}
    description: ${run_args.description}
    tracking_uri: 'http://localhost:5002' # sqlite:///mlruns/mlruns.db



args:
  output_dir: "data/7_finetuning/latn-large-lr"
  model: "meta-llama/Llama-3.2-3B-instruct"
  dtype: ${object:torch.bfloat16}
  dataset_path: "HuggingFaceFW/fineweb-2"
  dataset_language: "ces_Latn"
  dataset_split: "train"
  num_train_examples: 240000
  num_val_examples: 1000
  max_length: 2048
  batch_size: 4
  grad_accum: 2
  eval_batch_size: 4
  learning_rate: 2e-3
  epochs: 1
  eval_every_steps: 1000
  save_steps: 120000
  logging_steps: 10
  weight_decay: 0.0
  selected_neurons_path: "data/3_output/20-languages-latn/lape_selected_neurons.pt"
  train_languages: null
  exclude_languages:
    - "en_Latn"
    - "ces_Latn"

dataset:
  _target_: datasets.load_dataset
  path: ${args.dataset_path}
  name: ${args.dataset_language}
  split: ${args.dataset_split}
  streaming: true

dataset_train:
  _target_: finetuning_impl.7_finetuning.take
  dataset: ${dataset}
  num_take: ${args.num_train_examples}

dataset_valid:
  _target_: finetuning_impl.7_finetuning.shard_take
  dataset: ${dataset}
  num_shards: 20
  index: 19
  num_take: ${args.num_val_examples}

tokenizer:
  _target_: finetuning_impl.7_finetuning.load_tokenizer
  _args_:
    - ${args.model}

model:
  _target_: finetuning_impl.7_finetuning.load_masked_model
  _args_:
    - ${args.model}
  selected_neurons_path: ${args.selected_neurons_path}
  train_languages: ${args.train_languages}
  exclude_languages: ${args.exclude_languages}
  torch_dtype: ${args.dtype}

trainer:
  _target_: trl.SFTTrainer
  model: ${model}
  train_dataset: ${dataset_train}
  processing_class: ${tokenizer}
  eval_dataset: ${dataset_valid}
  callbacks:
    - _target_: runexp.TrackerTrainerCallback
      tracker: ${run_args.tracker}
      log_artifacts: false
  args:
    _target_: trl.SFTConfig
    output_dir: ${args.output_dir}
    max_length: ${args.max_length}
    per_device_train_batch_size: ${args.batch_size}
    gradient_accumulation_steps: ${args.grad_accum}
    per_device_eval_batch_size: ${args.eval_batch_size}
    learning_rate: ${args.learning_rate}
    weight_decay: ${args.weight_decay}
    num_train_epochs: ${args.epochs}
    max_steps: ${eval:'${args.num_train_examples} // (${args.batch_size} * ${args.grad_accum})'}
    report_to: []
    dataset_text_field: "text"
    eval_strategy: "steps"
    eval_steps: ${args.eval_every_steps}
    save_steps: ${args.save_steps}
    logging_steps: ${args.logging_steps}
    load_best_model_at_end: false
    metric_for_best_model: "eval_loss"
    greater_is_better: false
